export interface ServiceTier {
  name: 'basic' | 'standard' | 'premium';
  priceMultiplier: number;
  features: string[];
  valueProps: string[];
  warranty: string;
  responseTime: string;
  additionalServices: string[];
}

export interface ServiceType {
  value: string;
  label: string;
  category: string;
  basePrice: number;
  tiers: {
    basic: ServiceTier;
    standard: ServiceTier;
    premium: ServiceTier;
  };
}

// Service categories for organization
export const SERVICE_CATEGORIES = {
  BEAUTY: 'Beauty & Wellness',
  HOME: 'Home Services',
  AUTOMOTIVE: 'Automotive',
  PROFESSIONAL: 'Professional Services',
  HEALTH: 'Health & Medical',
  EDUCATION: 'Education & Training',
  TECHNOLOGY: 'Technology & IT',
  CONSTRUCTION: 'Construction & Renovation',
  CLEANING: 'Cleaning & Maintenance',
  LEGAL: 'Legal & Financial',
  LOCKSMITH: 'Locksmith Services',
  ELECTRONICS: 'Electronics Repair',
  CAREER: 'Career Services',
  AESTHETICIAN: 'Aesthetician Services',
};

export const SERVICE_TYPES: ServiceType[] = [
  // Beauty & Wellness
  {
    value: 'hair_styling',
    label: 'Hair Styling',
    category: SERVICE_CATEGORIES.BEAUTY,
    basePrice: 75,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic styling', 'Standard products', '30-minute session'],
        valueProps: ['Professional styling', 'Quality products', 'Quick service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced styling', 'Premium products', '60-minute session', 'Color treatment'],
        valueProps: ['Expert styling', 'Premium products', 'Comprehensive service'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Style recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: [
          'Luxury styling',
          'Luxury products',
          '90-minute session',
          'Full color treatment',
        ],
        valueProps: ['Master stylist service', 'Luxury products', 'VIP treatment'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['VIP consultation', 'Personalized style plan'],
      },
    },
  },
  {
    value: 'nail_care',
    label: 'Nail Care',
    category: SERVICE_CATEGORIES.BEAUTY,
    basePrice: 45,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic manicure', 'Standard polish', '30-minute session'],
        valueProps: ['Professional care', 'Quality products'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Gel manicure', 'Premium polish', '60-minute session', 'Nail art'],
        valueProps: ['Expert care', 'Premium products', 'Creative designs'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Design recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury manicure', 'Luxury products', '90-minute session', 'Custom designs'],
        valueProps: ['Master technician service', 'Luxury products', 'VIP treatment'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['VIP consultation', 'Custom design creation'],
      },
    },
  },
  {
    value: 'massage_therapy',
    label: 'Massage Therapy',
    category: SERVICE_CATEGORIES.BEAUTY,
    basePrice: 85,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['30-minute session', 'Basic massage', 'Standard oils'],
        valueProps: ['Stress relief', 'Basic relaxation', 'Professional service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['60-minute session', 'Deep tissue massage', 'Premium oils', 'Hot stone therapy'],
        valueProps: ['Deep relaxation', 'Muscle tension relief', 'Premium experience'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Customized treatment'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: [
          '90-minute session',
          'Specialized massage',
          'Luxury oils',
          'Full body treatment',
        ],
        valueProps: ['Complete relaxation', 'Expert treatment', 'VIP experience'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['VIP consultation', 'Custom treatment plan'],
      },
    },
  },
  {
    value: 'facial_treatment',
    label: 'Facial Treatment',
    category: SERVICE_CATEGORIES.BEAUTY,
    basePrice: 65,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic facial', 'Standard products', '30-minute session'],
        valueProps: ['Skin refresh', 'Basic care', 'Professional service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic skin analysis'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced facial', 'Premium products', '60-minute session', 'Exfoliation'],
        valueProps: ['Deep cleansing', 'Premium care', 'Comprehensive treatment'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed skin analysis', 'Product recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury facial', 'Luxury products', '90-minute session', 'Full treatment'],
        valueProps: ['Complete skin care', 'Expert treatment', 'VIP experience'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['VIP skin analysis', 'Custom treatment plan'],
      },
    },
  },

  // Home Services
  {
    value: 'plumbing',
    label: 'Plumbing Services',
    category: SERVICE_CATEGORIES.HOME,
    basePrice: 95,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic repair', 'Standard parts', '2-hour service window'],
        valueProps: ['Reliable repair', 'Quality parts', 'Professional service'],
        warranty: '30-day parts & labor warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic inspection'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: [
          'Comprehensive repair',
          'Premium parts',
          '1-hour service window',
          'Preventive maintenance',
        ],
        valueProps: ['Expert repair', 'Premium parts', 'Comprehensive service'],
        warranty: '90-day parts & labor warranty',
        responseTime: 'Same day',
        additionalServices: ['Detailed inspection', 'Maintenance recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: [
          'Complete system service',
          'Premium parts',
          '30-minute service window',
          'Emergency service',
        ],
        valueProps: ['Master plumber service', 'Premium parts', 'VIP treatment'],
        warranty: '1-year parts & labor warranty',
        responseTime: '2-hour window',
        additionalServices: ['System inspection', 'Preventive maintenance plan'],
      },
    },
  },
  {
    value: 'electrical',
    label: 'Electrical Services',
    category: SERVICE_CATEGORIES.HOME,
    basePrice: 85,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic electrical repair', 'Standard parts', '2-hour service window'],
        valueProps: ['Safe repair', 'Quality parts', 'Professional service'],
        warranty: '30-day parts & labor warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic safety inspection'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Comprehensive electrical work', 'Premium parts', '1-hour service window'],
        valueProps: ['Expert electrical work', 'Premium parts', 'Comprehensive service'],
        warranty: '90-day parts & labor warranty',
        responseTime: 'Same day',
        additionalServices: ['Detailed safety inspection', 'Upgrade recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete electrical system service', 'Premium parts', 'Emergency service'],
        valueProps: ['Master electrician service', 'Premium parts', 'VIP treatment'],
        warranty: '1-year parts & labor warranty',
        responseTime: '2-hour window',
        additionalServices: ['System inspection', 'Safety upgrade plan'],
      },
    },
  },
  {
    value: 'hvac',
    label: 'HVAC Services',
    category: SERVICE_CATEGORIES.HOME,
    basePrice: 90,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic maintenance', 'Standard parts', '2-hour service window'],
        valueProps: ['System check', 'Basic repair', 'Professional service'],
        warranty: '30-day parts & labor warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic inspection'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Comprehensive maintenance', 'Premium parts', '1-hour service window'],
        valueProps: ['System optimization', 'Premium repair', 'Priority service'],
        warranty: '90-day parts & labor warranty',
        responseTime: 'Same day',
        additionalServices: ['Detailed inspection', 'Efficiency recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete system service', 'Premium parts', 'Emergency service'],
        valueProps: ['System upgrade', 'Expert repair', 'VIP treatment'],
        warranty: '1-year parts & labor warranty',
        responseTime: '2-hour window',
        additionalServices: ['System audit', 'Efficiency upgrade plan'],
      },
    },
  },
  {
    value: 'carpentry',
    label: 'Carpentry Services',
    category: SERVICE_CATEGORIES.HOME,
    basePrice: 85,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic repairs', 'Standard materials', 'Standard service'],
        valueProps: ['Quality work', 'Basic repairs', 'Professional service'],
        warranty: '30-day workmanship warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Custom work', 'Premium materials', 'Priority service'],
        valueProps: ['Custom solutions', 'Premium quality', 'Expert service'],
        warranty: '90-day workmanship warranty',
        responseTime: 'Same day',
        additionalServices: ['Detailed consultation', 'Design recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Custom design', 'Premium materials', 'VIP service'],
        valueProps: ['Bespoke solutions', 'Premium quality', 'VIP treatment'],
        warranty: '1-year workmanship warranty',
        responseTime: '2-hour window',
        additionalServices: ['Design consultation', 'Custom design plan'],
      },
    },
  },

  // Automotive
  {
    value: 'auto_repair',
    label: 'Auto Repair',
    category: SERVICE_CATEGORIES.AUTOMOTIVE,
    basePrice: 90,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic repair', 'Standard parts', 'Standard service'],
        valueProps: ['Reliable repair', 'Quality parts', 'Professional service'],
        warranty: '30-day parts & labor warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic inspection'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Comprehensive repair', 'Premium parts', 'Priority service'],
        valueProps: ['Expert repair', 'Premium parts', 'Comprehensive service'],
        warranty: '90-day parts & labor warranty',
        responseTime: 'Same day',
        additionalServices: ['Detailed inspection', 'Maintenance recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete system service', 'Premium parts', 'VIP service'],
        valueProps: ['Master mechanic service', 'Premium parts', 'VIP treatment'],
        warranty: '1-year parts & labor warranty',
        responseTime: '2-hour window',
        additionalServices: ['System inspection', 'Preventive maintenance plan'],
      },
    },
  },
  {
    value: 'tire_service',
    label: 'Tire Service',
    category: SERVICE_CATEGORIES.AUTOMOTIVE,
    basePrice: 75,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic tire service', 'Standard tires', 'Standard service'],
        valueProps: ['Quality service', 'Basic maintenance', 'Professional work'],
        warranty: '30-day service warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic inspection'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Premium tire service', 'Premium tires', 'Priority service'],
        valueProps: ['Premium service', 'Quality maintenance', 'Expert work'],
        warranty: '90-day service warranty',
        responseTime: 'Same day',
        additionalServices: ['Detailed inspection', 'Maintenance recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['VIP tire service', 'Premium tires', 'VIP service'],
        valueProps: ['VIP service', 'Premium maintenance', 'Expert work'],
        warranty: '1-year service warranty',
        responseTime: '2-hour window',
        additionalServices: ['Comprehensive inspection', 'Maintenance plan'],
      },
    },
  },
  {
    value: 'auto_detailing',
    label: 'Auto Detailing',
    category: SERVICE_CATEGORIES.AUTOMOTIVE,
    basePrice: 80,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic wash', 'Interior cleaning', 'Standard service'],
        valueProps: ['Clean vehicle', 'Basic detailing', 'Professional service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '24-48 hours',
        additionalServices: ['Basic inspection'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Premium wash', 'Deep cleaning', 'Priority service'],
        valueProps: ['Premium detailing', 'Deep cleaning', 'Expert service'],
        warranty: '7-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['Detailed inspection', 'Care recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['VIP detailing', 'Complete restoration', 'VIP service'],
        valueProps: ['VIP detailing', 'Complete restoration', 'Expert service'],
        warranty: '14-day satisfaction guarantee',
        responseTime: '2-hour window',
        additionalServices: ['Comprehensive inspection', 'Care plan'],
      },
    },
  },

  // Professional Services
  {
    value: 'legal_consultation',
    label: 'Legal Consultation',
    category: SERVICE_CATEGORIES.PROFESSIONAL,
    basePrice: 150,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic consultation', 'Standard legal advice', '30-minute session'],
        valueProps: ['Professional advice', 'Clear guidance', 'Quick service'],
        warranty: 'N/A',
        responseTime: '48 hours',
        additionalServices: ['Basic document review'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Comprehensive consultation', 'Detailed legal advice', '60-minute session'],
        valueProps: ['Expert advice', 'Detailed guidance', 'Comprehensive service'],
        warranty: 'N/A',
        responseTime: '24 hours',
        additionalServices: ['Detailed document review', 'Strategy recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['VIP consultation', 'Expert legal advice', '90-minute session'],
        valueProps: ['Master attorney service', 'VIP treatment', 'Complete guidance'],
        warranty: 'N/A',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive document review', 'Strategic planning'],
      },
    },
  },
  {
    value: 'accounting',
    label: 'Accounting Services',
    category: SERVICE_CATEGORIES.PROFESSIONAL,
    basePrice: 120,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic bookkeeping', 'Tax preparation', 'Standard service'],
        valueProps: ['Accurate records', 'Basic accounting', 'Professional service'],
        warranty: 'N/A',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced bookkeeping', 'Tax planning', 'Priority service'],
        valueProps: ['Comprehensive records', 'Advanced accounting', 'Expert service'],
        warranty: 'N/A',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Financial recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Full accounting', 'Strategic planning', 'VIP service'],
        valueProps: ['Complete accounting', 'Strategic planning', 'Expert service'],
        warranty: 'N/A',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive consultation', 'Strategic plan'],
      },
    },
  },
  {
    value: 'business_consulting',
    label: 'Business Consulting',
    category: SERVICE_CATEGORIES.PROFESSIONAL,
    basePrice: 200,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic consultation', 'Strategy review', 'Standard service'],
        valueProps: ['Business insights', 'Basic strategy', 'Professional service'],
        warranty: 'N/A',
        responseTime: '48 hours',
        additionalServices: ['Basic analysis'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Comprehensive consultation', 'Strategy development', 'Priority service'],
        valueProps: ['Business optimization', 'Advanced strategy', 'Expert service'],
        warranty: 'N/A',
        responseTime: '24 hours',
        additionalServices: ['Detailed analysis', 'Strategy recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['VIP consultation', 'Strategic planning', 'VIP service'],
        valueProps: ['Business transformation', 'Strategic planning', 'Expert service'],
        warranty: 'N/A',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive analysis', 'Strategic plan'],
      },
    },
  },

  // Technology & IT
  {
    value: 'it_support',
    label: 'IT Support',
    category: SERVICE_CATEGORIES.TECHNOLOGY,
    basePrice: 80,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic troubleshooting', 'Standard support', 'Remote assistance'],
        valueProps: ['Quick resolution', 'Professional support', 'Efficient service'],
        warranty: '30-day support guarantee',
        responseTime: '24-48 hours',
        additionalServices: ['Basic system check'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Comprehensive support', 'Premium assistance', 'On-site support'],
        valueProps: ['Expert support', 'Comprehensive service', 'Priority handling'],
        warranty: '90-day support guarantee',
        responseTime: 'Same day',
        additionalServices: ['System optimization', 'Security recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['VIP support', '24/7 assistance', 'Dedicated technician'],
        valueProps: ['Master technician service', 'VIP treatment', 'Complete support'],
        warranty: '1-year support guarantee',
        responseTime: '2-hour window',
        additionalServices: ['System audit', 'Security implementation'],
      },
    },
  },
  {
    value: 'web_development',
    label: 'Web Development',
    category: SERVICE_CATEGORIES.TECHNOLOGY,
    basePrice: 100,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic website', 'Standard design', 'Standard service'],
        valueProps: ['Online presence', 'Basic website', 'Professional service'],
        warranty: '30-day support guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Custom website', 'Premium design', 'Priority service'],
        valueProps: ['Custom website', 'Premium design', 'Expert service'],
        warranty: '90-day support guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Design recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['E-commerce website', 'Premium design', 'VIP service'],
        valueProps: ['Complete solution', 'Premium design', 'Expert service'],
        warranty: '1-year support guarantee',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive consultation', 'Design plan'],
      },
    },
  },
  {
    value: 'network_setup',
    label: 'Network Setup',
    category: SERVICE_CATEGORIES.TECHNOLOGY,
    basePrice: 90,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic setup', 'Standard equipment', 'Standard service'],
        valueProps: ['Network setup', 'Basic configuration', 'Professional service'],
        warranty: '30-day support guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced setup', 'Premium equipment', 'Priority service'],
        valueProps: ['Advanced setup', 'Premium configuration', 'Expert service'],
        warranty: '90-day support guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Setup recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete setup', 'Premium equipment', 'VIP service'],
        valueProps: ['Complete setup', 'Premium configuration', 'Expert service'],
        warranty: '1-year support guarantee',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive consultation', 'Setup plan'],
      },
    },
  },

  // Construction & Renovation
  {
    value: 'home_renovation',
    label: 'Home Renovation',
    category: SERVICE_CATEGORIES.CONSTRUCTION,
    basePrice: 120,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic renovation', 'Standard materials', 'Standard service'],
        valueProps: ['Quality renovation', 'Basic updates', 'Professional service'],
        warranty: '1-year workmanship warranty',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Custom renovation', 'Premium materials', 'Priority service'],
        valueProps: ['Custom renovation', 'Premium updates', 'Expert service'],
        warranty: '2-year workmanship warranty',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Design recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury renovation', 'Premium materials', 'VIP service'],
        valueProps: ['Luxury renovation', 'Premium updates', 'Expert service'],
        warranty: '3-year workmanship warranty',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive consultation', 'Design plan'],
      },
    },
  },
  {
    value: 'kitchen_remodel',
    label: 'Kitchen Remodel',
    category: SERVICE_CATEGORIES.CONSTRUCTION,
    basePrice: 150,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic remodel', 'Standard materials', 'Standard service'],
        valueProps: ['Quality remodel', 'Basic updates', 'Professional service'],
        warranty: '1-year workmanship warranty',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Custom remodel', 'Premium materials', 'Priority service'],
        valueProps: ['Custom remodel', 'Premium updates', 'Expert service'],
        warranty: '2-year workmanship warranty',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Design recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury remodel', 'Premium materials', 'VIP service'],
        valueProps: ['Luxury remodel', 'Premium updates', 'Expert service'],
        warranty: '3-year workmanship warranty',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive consultation', 'Design plan'],
      },
    },
  },

  // Cleaning & Maintenance
  {
    value: 'house_cleaning',
    label: 'House Cleaning',
    category: SERVICE_CATEGORIES.CLEANING,
    basePrice: 60,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic cleaning', 'Standard service', 'Standard products'],
        valueProps: ['Clean home', 'Basic cleaning', 'Professional service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Deep cleaning', 'Priority service', 'Premium products'],
        valueProps: ['Deep cleaning', 'Premium service', 'Expert cleaning'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Cleaning recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury cleaning', 'VIP service', 'Premium products'],
        valueProps: ['Luxury cleaning', 'VIP service', 'Expert cleaning'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive consultation', 'Cleaning plan'],
      },
    },
  },
  {
    value: 'carpet_cleaning',
    label: 'Carpet Cleaning',
    category: SERVICE_CATEGORIES.CLEANING,
    basePrice: 70,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic cleaning', 'Standard service', 'Standard products'],
        valueProps: ['Clean carpets', 'Basic cleaning', 'Professional service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic inspection'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Deep cleaning', 'Priority service', 'Premium products'],
        valueProps: ['Deep cleaning', 'Premium service', 'Expert cleaning'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed inspection', 'Cleaning recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury cleaning', 'VIP service', 'Premium products'],
        valueProps: ['Luxury cleaning', 'VIP service', 'Expert cleaning'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive inspection', 'Cleaning plan'],
      },
    },
  },

  // Legal & Financial
  {
    value: 'tax_preparation',
    label: 'Tax Preparation',
    category: SERVICE_CATEGORIES.LEGAL,
    basePrice: 130,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic preparation', 'Standard service', 'Basic filing'],
        valueProps: ['Accurate filing', 'Basic preparation', 'Professional service'],
        warranty: 'N/A',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced preparation', 'Priority service', 'Advanced filing'],
        valueProps: ['Advanced filing', 'Premium service', 'Expert preparation'],
        warranty: 'N/A',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Tax recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete preparation', 'VIP service', 'Complete filing'],
        valueProps: ['Complete filing', 'VIP service', 'Expert preparation'],
        warranty: 'N/A',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive consultation', 'Tax plan'],
      },
    },
  },
  {
    value: 'financial_planning',
    label: 'Financial Planning',
    category: SERVICE_CATEGORIES.LEGAL,
    basePrice: 140,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic planning', 'Standard service', 'Basic analysis'],
        valueProps: ['Basic planning', 'Standard service', 'Professional advice'],
        warranty: 'N/A',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced planning', 'Priority service', 'Advanced analysis'],
        valueProps: ['Advanced planning', 'Premium service', 'Expert advice'],
        warranty: 'N/A',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Planning recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete planning', 'VIP service', 'Complete analysis'],
        valueProps: ['Complete planning', 'VIP service', 'Expert advice'],
        warranty: 'N/A',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive consultation', 'Financial plan'],
      },
    },
  },

  // Locksmith Services
  {
    value: 'emergency_locksmith',
    label: 'Emergency Locksmith',
    category: SERVICE_CATEGORIES.LOCKSMITH,
    basePrice: 100,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic lockout service', 'Standard lock replacement', '24/7 emergency service'],
        valueProps: ['Quick response', 'Basic security', 'Professional service'],
        warranty: '30-day service warranty',
        responseTime: '30-60 minutes',
        additionalServices: ['Basic security assessment'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: [
          'Advanced lockout service',
          'Premium lock replacement',
          'Priority emergency service',
        ],
        valueProps: ['Fast response', 'Enhanced security', 'Expert service'],
        warranty: '90-day service warranty',
        responseTime: '15-30 minutes',
        additionalServices: ['Security assessment', 'Upgrade recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: [
          'VIP lockout service',
          'High-security lock replacement',
          'Immediate emergency service',
        ],
        valueProps: ['Immediate response', 'Maximum security', 'VIP service'],
        warranty: '1-year service warranty',
        responseTime: '10-15 minutes',
        additionalServices: ['Comprehensive security assessment', 'Security upgrade plan'],
      },
    },
  },
  {
    value: 'security_installation',
    label: 'Security Installation',
    category: SERVICE_CATEGORIES.LOCKSMITH,
    basePrice: 120,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic security system', 'Standard installation', 'Basic monitoring'],
        valueProps: ['Basic security', 'Professional installation', 'Standard monitoring'],
        warranty: '1-year installation warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic security consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced security system', 'Premium installation', 'Enhanced monitoring'],
        valueProps: ['Enhanced security', 'Expert installation', 'Advanced monitoring'],
        warranty: '2-year installation warranty',
        responseTime: 'Same day',
        additionalServices: ['Security consultation', 'System recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete security system', 'Premium installation', '24/7 monitoring'],
        valueProps: ['Complete security', 'Expert installation', '24/7 monitoring'],
        warranty: '3-year installation warranty',
        responseTime: '2-hour window',
        additionalServices: ['Comprehensive security consultation', 'Custom security plan'],
      },
    },
  },

  // Electronics Repair
  {
    value: 'phone_repair',
    label: 'Phone Repair',
    category: SERVICE_CATEGORIES.ELECTRONICS,
    basePrice: 85,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic repairs', 'Standard parts', 'Standard service'],
        valueProps: ['Quick repair', 'Quality parts', 'Professional service'],
        warranty: '30-day repair warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic diagnostics'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced repairs', 'Premium parts', 'Priority service'],
        valueProps: ['Expert repair', 'Premium parts', 'Fast service'],
        warranty: '90-day repair warranty',
        responseTime: 'Same day',
        additionalServices: ['Detailed diagnostics', 'Maintenance recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete repair', 'Premium parts', 'VIP service'],
        valueProps: ['Complete repair', 'Premium parts', 'VIP treatment'],
        warranty: '1-year repair warranty',
        responseTime: '2-hour window',
        additionalServices: ['Comprehensive diagnostics', 'Maintenance plan'],
      },
    },
  },
  {
    value: 'computer_repair',
    label: 'Computer Repair',
    category: SERVICE_CATEGORIES.ELECTRONICS,
    basePrice: 95,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic repairs', 'Standard parts', 'Standard service'],
        valueProps: ['Quick repair', 'Quality parts', 'Professional service'],
        warranty: '30-day repair warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic diagnostics'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced repairs', 'Premium parts', 'Priority service'],
        valueProps: ['Expert repair', 'Premium parts', 'Fast service'],
        warranty: '90-day repair warranty',
        responseTime: 'Same day',
        additionalServices: ['Detailed diagnostics', 'Upgrade recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete repair', 'Premium parts', 'VIP service'],
        valueProps: ['Complete repair', 'Premium parts', 'VIP treatment'],
        warranty: '1-year repair warranty',
        responseTime: '2-hour window',
        additionalServices: ['Comprehensive diagnostics', 'Upgrade plan'],
      },
    },
  },

  // Career Services
  {
    value: 'resume_writing',
    label: 'Resume Writing',
    category: SERVICE_CATEGORIES.CAREER,
    basePrice: 150,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic resume', 'Standard formatting', 'Basic review'],
        valueProps: ['Professional resume', 'Basic optimization', 'Standard service'],
        warranty: 'N/A',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced resume', 'Premium formatting', 'Detailed review'],
        valueProps: ['Optimized resume', 'Premium formatting', 'Expert service'],
        warranty: 'N/A',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Career recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Executive resume', 'Premium formatting', 'Complete review'],
        valueProps: ['Executive resume', 'Premium formatting', 'VIP service'],
        warranty: 'N/A',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive consultation', 'Career strategy'],
      },
    },
  },
  {
    value: 'career_coaching',
    label: 'Career Coaching',
    category: SERVICE_CATEGORIES.CAREER,
    basePrice: 180,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic coaching', 'Standard sessions', 'Basic guidance'],
        valueProps: ['Career guidance', 'Basic coaching', 'Professional service'],
        warranty: 'N/A',
        responseTime: '48 hours',
        additionalServices: ['Basic assessment'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced coaching', 'Premium sessions', 'Detailed guidance'],
        valueProps: ['Career development', 'Premium coaching', 'Expert service'],
        warranty: 'N/A',
        responseTime: '24 hours',
        additionalServices: ['Detailed assessment', 'Development plan'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Executive coaching', 'Premium sessions', 'Complete guidance'],
        valueProps: ['Career transformation', 'Premium coaching', 'VIP service'],
        warranty: 'N/A',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive assessment', 'Transformation plan'],
      },
    },
  },

  // Additional Technology Services
  {
    value: 'mobile_app_development',
    label: 'Mobile App Development',
    category: SERVICE_CATEGORIES.TECHNOLOGY,
    basePrice: 150,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic app', 'Standard design', 'Basic features'],
        valueProps: ['Functional app', 'Basic design', 'Professional service'],
        warranty: '30-day support guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Custom app', 'Premium design', 'Advanced features'],
        valueProps: ['Custom app', 'Premium design', 'Expert service'],
        warranty: '90-day support guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Feature recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Enterprise app', 'Premium design', 'Complete features'],
        valueProps: ['Enterprise app', 'Premium design', 'VIP service'],
        warranty: '1-year support guarantee',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive consultation', 'Development plan'],
      },
    },
  },
  {
    value: 'software_development',
    label: 'Software Development',
    category: SERVICE_CATEGORIES.TECHNOLOGY,
    basePrice: 200,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic software', 'Standard development', 'Basic features'],
        valueProps: ['Functional software', 'Basic development', 'Professional service'],
        warranty: '30-day support guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Custom software', 'Premium development', 'Advanced features'],
        valueProps: ['Custom software', 'Premium development', 'Expert service'],
        warranty: '90-day support guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Feature recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Enterprise software', 'Premium development', 'Complete features'],
        valueProps: ['Enterprise software', 'Premium development', 'VIP service'],
        warranty: '1-year support guarantee',
        responseTime: 'Same day',
        additionalServices: ['Comprehensive consultation', 'Development plan'],
      },
    },
  },

  // Additional Beauty & Wellness Services
  {
    value: 'makeup_artistry',
    label: 'Makeup Artistry',
    category: SERVICE_CATEGORIES.BEAUTY,
    basePrice: 90,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic makeup', 'Standard products', '30-minute session'],
        valueProps: ['Professional makeup', 'Quality products', 'Quick service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced makeup', 'Premium products', '60-minute session', 'Contouring'],
        valueProps: ['Expert makeup', 'Premium products', 'Comprehensive service'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Style recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury makeup', 'Luxury products', '90-minute session', 'Full glam'],
        valueProps: ['Master artist service', 'Luxury products', 'VIP treatment'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['VIP consultation', 'Personalized style plan'],
      },
    },
  },
  {
    value: 'spa_treatment',
    label: 'Spa Treatment',
    category: SERVICE_CATEGORIES.BEAUTY,
    basePrice: 120,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic treatment', 'Standard products', '60-minute session'],
        valueProps: ['Relaxation', 'Basic treatment', 'Professional service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced treatment', 'Premium products', '90-minute session', 'Aromatherapy'],
        valueProps: ['Deep relaxation', 'Premium treatment', 'Expert service'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Treatment recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury treatment', 'Luxury products', '120-minute session', 'Full experience'],
        valueProps: ['Complete relaxation', 'Luxury treatment', 'VIP service'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['VIP consultation', 'Custom treatment plan'],
      },
    },
  },

  // Additional Locksmith Services
  {
    value: 'safe_installation',
    label: 'Safe Installation',
    category: SERVICE_CATEGORIES.LOCKSMITH,
    basePrice: 150,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic safe installation', 'Standard mounting', 'Basic security'],
        valueProps: ['Secure installation', 'Professional service', 'Basic security'],
        warranty: '1-year installation warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic security assessment'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced safe installation', 'Premium mounting', 'Enhanced security'],
        valueProps: ['Secure installation', 'Expert service', 'Enhanced security'],
        warranty: '2-year installation warranty',
        responseTime: 'Same day',
        additionalServices: ['Security assessment', 'Upgrade recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury safe installation', 'Premium mounting', 'Maximum security'],
        valueProps: ['Secure installation', 'VIP service', 'Maximum security'],
        warranty: '3-year installation warranty',
        responseTime: '2-hour window',
        additionalServices: ['Comprehensive security assessment', 'Security upgrade plan'],
      },
    },
  },
  {
    value: 'access_control',
    label: 'Access Control Systems',
    category: SERVICE_CATEGORIES.LOCKSMITH,
    basePrice: 200,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic system', 'Standard installation', 'Basic control'],
        valueProps: ['Access control', 'Professional installation', 'Basic security'],
        warranty: '1-year installation warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced system', 'Premium installation', 'Enhanced control'],
        valueProps: ['Advanced control', 'Expert installation', 'Enhanced security'],
        warranty: '2-year installation warranty',
        responseTime: 'Same day',
        additionalServices: ['Detailed consultation', 'System recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete system', 'Premium installation', 'Full control'],
        valueProps: ['Complete control', 'Expert installation', 'Maximum security'],
        warranty: '3-year installation warranty',
        responseTime: '2-hour window',
        additionalServices: ['Comprehensive consultation', 'System upgrade plan'],
      },
    },
  },

  // Additional Electronics Repair Services
  {
    value: 'tablet_repair',
    label: 'Tablet Repair',
    category: SERVICE_CATEGORIES.ELECTRONICS,
    basePrice: 90,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic repairs', 'Standard parts', 'Standard service'],
        valueProps: ['Quick repair', 'Quality parts', 'Professional service'],
        warranty: '30-day repair warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic diagnostics'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced repairs', 'Premium parts', 'Priority service'],
        valueProps: ['Expert repair', 'Premium parts', 'Fast service'],
        warranty: '90-day repair warranty',
        responseTime: 'Same day',
        additionalServices: ['Detailed diagnostics', 'Maintenance recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete repair', 'Premium parts', 'VIP service'],
        valueProps: ['Complete repair', 'Premium parts', 'VIP treatment'],
        warranty: '1-year repair warranty',
        responseTime: '2-hour window',
        additionalServices: ['Comprehensive diagnostics', 'Maintenance plan'],
      },
    },
  },
  {
    value: 'smart_home_repair',
    label: 'Smart Home Repair',
    category: SERVICE_CATEGORIES.ELECTRONICS,
    basePrice: 110,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic repairs', 'Standard parts', 'Standard service'],
        valueProps: ['Quick repair', 'Quality parts', 'Professional service'],
        warranty: '30-day repair warranty',
        responseTime: '24-48 hours',
        additionalServices: ['Basic diagnostics'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced repairs', 'Premium parts', 'Priority service'],
        valueProps: ['Expert repair', 'Premium parts', 'Fast service'],
        warranty: '90-day repair warranty',
        responseTime: 'Same day',
        additionalServices: ['Detailed diagnostics', 'Upgrade recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Complete repair', 'Premium parts', 'VIP service'],
        valueProps: ['Complete repair', 'Premium parts', 'VIP treatment'],
        warranty: '1-year repair warranty',
        responseTime: '2-hour window',
        additionalServices: ['Comprehensive diagnostics', 'Upgrade plan'],
      },
    },
  },

  // Aesthetician Services
  {
    value: 'facial_treatment',
    label: 'Facial Treatment',
    category: SERVICE_CATEGORIES.AESTHETICIAN,
    basePrice: 85,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic facial', 'Standard products', '30-minute session'],
        valueProps: ['Skin refresh', 'Basic care', 'Professional service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic skin analysis'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: ['Advanced facial', 'Premium products', '60-minute session', 'Exfoliation'],
        valueProps: ['Deep cleansing', 'Premium care', 'Comprehensive treatment'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed skin analysis', 'Product recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury facial', 'Luxury products', '90-minute session', 'Full treatment'],
        valueProps: ['Complete skin care', 'Expert treatment', 'VIP experience'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['VIP skin analysis', 'Custom treatment plan'],
      },
    },
  },
  {
    value: 'skin_treatment',
    label: 'Skin Treatment',
    category: SERVICE_CATEGORIES.AESTHETICIAN,
    basePrice: 120,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic treatment', 'Standard products', '30-minute session'],
        valueProps: ['Skin improvement', 'Basic care', 'Professional service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: [
          'Advanced treatment',
          'Premium products',
          '60-minute session',
          'Specialized care',
        ],
        valueProps: ['Skin enhancement', 'Premium care', 'Expert service'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Treatment recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury treatment', 'Luxury products', '90-minute session', 'Complete care'],
        valueProps: ['Skin transformation', 'Luxury care', 'VIP service'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['VIP consultation', 'Custom treatment plan'],
      },
    },
  },
  {
    value: 'body_treatment',
    label: 'Body Treatment',
    category: SERVICE_CATEGORIES.AESTHETICIAN,
    basePrice: 150,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic treatment', 'Standard products', '60-minute session'],
        valueProps: ['Body refresh', 'Basic care', 'Professional service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: [
          'Advanced treatment',
          'Premium products',
          '90-minute session',
          'Specialized care',
        ],
        valueProps: ['Body enhancement', 'Premium care', 'Expert service'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Treatment recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury treatment', 'Luxury products', '120-minute session', 'Complete care'],
        valueProps: ['Body transformation', 'Luxury care', 'VIP service'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['VIP consultation', 'Custom treatment plan'],
      },
    },
  },
  {
    value: 'hair_removal',
    label: 'Hair Removal',
    category: SERVICE_CATEGORIES.AESTHETICIAN,
    basePrice: 95,
    tiers: {
      basic: {
        name: 'basic',
        priceMultiplier: 1,
        features: ['Basic treatment', 'Standard service', '30-minute session'],
        valueProps: ['Hair removal', 'Basic care', 'Professional service'],
        warranty: '24-hour satisfaction guarantee',
        responseTime: '48 hours',
        additionalServices: ['Basic consultation'],
      },
      standard: {
        name: 'standard',
        priceMultiplier: 1.5,
        features: [
          'Advanced treatment',
          'Premium service',
          '60-minute session',
          'Specialized care',
        ],
        valueProps: ['Premium removal', 'Enhanced care', 'Expert service'],
        warranty: '7-day satisfaction guarantee',
        responseTime: '24 hours',
        additionalServices: ['Detailed consultation', 'Treatment recommendations'],
      },
      premium: {
        name: 'premium',
        priceMultiplier: 2.5,
        features: ['Luxury treatment', 'Premium service', '90-minute session', 'Complete care'],
        valueProps: ['Luxury removal', 'Premium care', 'VIP service'],
        warranty: '14-day satisfaction guarantee',
        responseTime: 'Same day',
        additionalServices: ['VIP consultation', 'Custom treatment plan'],
      },
    },
  },
];

// Helper function to get services by category
export const getServicesByCategory = () => {
  return SERVICE_TYPES.reduce(
    (acc, service) => {
      if (!acc[service.category]) {
        acc[service.category] = [];
      }
      acc[service.category].push(service);
      return acc;
    },
    {} as Record<string, ServiceType[]>
  );
};

export const _getServiceTierFeatures = (
  serviceType: string,
  tier: 'basic' | 'standard' | 'premium'
): ServiceTier => {
  const service = SERVICE_TYPES.find(s => s.value === serviceType);
  if (!service) {
    throw new Error(`Service type ${serviceType} not found`);
  }
  return service.tiers[tier];
};

export const _calculateTierPrice = () => 0;
